### Hello World
GET / HTTP/1.1
Host: localhost:3333

### Create ong
POST /ongs HTTP/1.1
Host: localhost:3333
Content-Type: application/json

{
  "name": "APAD",
  "email": "email@teste.com",
  "whatsapp": "00 00000 0000",
  "city": "Curitiba",
  "uf": "PR"
}

### List ongs
GET /ongs HTTP/1.1
Host: localhost:3333
Content-Type: application/json

### Create ong
POST /incidents HTTP/1.1
Host: localhost:3333
Content-Type: application/json
Authorization: '93acbe59'

{
  "title": "Caso 1",
  "description": "Detalhes do caso",
  "value": 120
}

### List incidents
GET /incidents?page=2 HTTP/1.1
Host: localhost:3333
Content-Type: application/json

### Create ong
DELETE  /incidents/1 HTTP/1.1
Host: localhost:3333
Content-Type: application/json
Authorization: '93acbe59'


### Profile
GET /profile HTTP/1.1
Host: localhost:3333
Content-Type: application/json
Authorization: '93acbe59'

### Login
POST /sessions HTTP/1.1
Host: localhost:3333
Content-Type: application/json

{
  "id": "93acbe59"
}