### Hello World
GET / HTTP/1.1
Host: localhost:3333

### Create ong
POST /ongs HTTP/1.1
Host: localhost:3333
Content-Type: application/json

{
  "name": "APAD",
  "email": "email@teste.com",
  "whatsapp": "00 00000 0000",
  "city": "Curitiba",
  "uf": "PR"
}

### List ongs
GET /ongs HTTP/1.1
Host: localhost:3333
Content-Type: application/json

### 